### ISSUE TITLE
Not able to connect to DB instances in other spaces

### ISSUE THREAD

**Issue by ichandan16** [pivotal-cf/PivotalMySQLWeb#24]
Hi, I tried to push the application to a space without binding to a mysql service, hoping that it will act as a global app and connect to the DB instances with their respective credentials (username, password and JDBC string). However it does not work as expected. Below is the manifest.yml file.

```
---
applications:
- name: pivotal-mysqlweb
  memory: 1024M
  instances: 1
  path: ./target/PivotalMySQLWeb-1.0.0-SNAPSHOT.jar
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
```

1. Once the application is up and access page shows me default username and password page. 

![image](https://user-images.githubusercontent.com/9046793/103302081-c6aa3200-49d0-11eb-8961-3e49b5f11cb0.png)

Provided Default username = admin Default password = cfmysqlweb

2. It redirects me to the login page where it shows me the dialog box to input username, password and JDBC string. 

![image](https://user-images.githubusercontent.com/9046793/103302180-0244fc00-49d1-11eb-9cc1-1a57025e8cda.png)

3. Provided the correct credentials (verified multiple times, created service-keys and used the values, tried both bosh dns or IP of the service instance). it fails with bad credentials & displays me the initial login page where we are providing the default credentials.

![image](https://user-images.githubusercontent.com/9046793/103302361-767f9f80-49d1-11eb-9073-63509d4819ce.png)
  
However, if I push this application to the space where the applications DB is running and in manifest.yml, provide the application service instance name, it works with default user name and password. It does not ask for service instance username, password and JDBC URL.

Thanks,
Chandan
